---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "add user for prometheus"
  become: yes
  shell: |
    useradd --no-create-home prometheus
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: "install prometheus"
  become: yes
  shell: |
    wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    tar xvfz prometheus-2.19.0.linux-amd64.tar.gz

    cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus

    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

- name: "allow prometheus availability as a service"
  become: yes
  shell: |
    touch /etc/systemd/system/prometheus.service
    sudo bash -c "echo -e '[Unit]\nDescription=Prometheus\nWants=network-online.target\nAfter=network-online.target\n[Service]\nUser=prometheus\nGroup=prometheus\nType=simple\nExecStart=/usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries\n[Install]\nWantedBy=multi-user.target' > /etc/systemd/system/prometheus.service"

- name: "change permisions of files"
  become: yes
  shell: |
    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

- name: "configure systemd"
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable prometheus